# Generated by Django 4.0 on 2022-06-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='hola@example.pe', max_length=254),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='example', max_length=20),
        ),
    ]
